### ISSUE TITLE
Server 2016 - Application unable to start correctly

### ISSUE THREAD

**Issue by Jonathan-Garber** [multiOTP/multiOTPCredentialProvider#31]
I tried install the latest 5.6.1.5 on Server 2016 but it won't install correctly.
php.exe Application Error
The application was unable to start correctly (0xc000007b). Click OK to close the application.

The Installer then shows
Check exit code - 1073741701 in multiotp documentation

Where is this documentation? I am not finding it.

Any pointers?

**Comment by Jonathan-Garber** [comment]
Just an update - I downloaded the full PHP from https://windows.php.net/download
and replaced PHP that the provider left in place and now PHP and Multiotp.exe work.

I think something went wrong with the installer and it goofed the install of PHP for some reason.

**Comment by multiOTP** [comment]
Hello Jonathan,
The new 5.8.0.2 version is available here : https://download.multiotp.net/credential-provider/
Please have a look, we have installed it on a clean Windows 2019 server without any problem.

Concerning exit code 1073741701, it's a unknown exit code for multiOTP, probably due to a bug during installation.

Best regards,

Andre

**Comment by Jonathan-Garber** [comment]
Yea, that one worked. Wonder why the other version burned.

I am actually using 5.6.1.5 Server with a ton of workstations still on 5.1.1.2 provider
So I am working on upgrading stations to the latest provider now and I ran into this.
