### ISSUE TITLE
NTP error

### ISSUE THREAD

**Issue by jonathanmmm** [multiOTP/multiOTPCredentialProvider#38]
Hi,

I have the newest release from github installed 5.6.1.5.

If my time from system changes (sometimes this happens, around an hour earlier) I have to change the time on my phone manually to also the wrong time to get the right code.

I saw that in the config there is a time server pool.ntp.org, I live in Germany, maybe I have to change this to de.pool.ntp.org or something like that? On the login screen I can see my Laptop is connected via wifi, so this shouldn't be a problem.

**Comment by multiOTP** [comment]
Hello,
By default, the "max_time_window=600" is set to 300 seconds, that's why you will have to change the time on your phone to be syncrhonized with the time of your server (+/- 300 seconds).
You  can also change your multiOTP setup by putting "max_time_window=3900" in order to allow 1 hour +/- 300 seconds of time window (in this case, please note that you can never type a token generated BEFORE the last accepted token).
Time servers give always the same time based on UTC, pool.ntp.org or de.pool.ntp.org or any others will always give the same time. The only thing that you have to be sure is to set correctly your timezone in your OS.
Regards,
