### ISSUE TITLE
Anyone can bypass multiOTP code input by reconnection

### ISSUE THREAD

**Issue by HumMan** [multiOTP/multiOTPCredentialProvider#4]
Hi,
I have the following environment:

**RDP server:**
Windows 10 64-bit Version 1709 (build 16299.248)
multiOTP CredentialProvider 5.1.0.1 installed in c:\multiOTP\
two factor authorization with multiotp is working
NLA enabled

**Client:**
Windows 10 64-bit Version 1709 (build 16299.248)

**Steps to bypass multiOTP code entering:**

1. Connect to the RDP session by entering a password only
![1](https://user-images.githubusercontent.com/2682978/37049912-7fc25ef8-2183-11e8-9c24-6c68d4b6b9ce.png)
2. Don't enter password and OTP code
![2](https://user-images.githubusercontent.com/2682978/37049913-7fde403c-2183-11e8-9322-4407dac53c1e.png)
3. Unplug ethernet cable to simulate a connection lost
4. Wait 15-20 seconds to reconnection message popupp
![3](https://user-images.githubusercontent.com/2682978/37049914-7ffa6118-2183-11e8-9820-e3cc1ed96d20.png)
5. Plug ethernet cable back
6. Reconnection success and you don't need to enter anything
![4](https://user-images.githubusercontent.com/2682978/37049911-7fa611e4-2183-11e8-80e9-450ea033c9f2.png)

Can you reproduce the bypass?

**Comment by HumMan** [comment]
Same behaviour in multiOTP CredentialProvider 5.1.0.8
Temp workaround is to disable the clients reconnection in group policy:
`Administrative templates -> Windows components -> Remote desktop services -> Remote desktop session host -> Connections -> Automatic reconnection = Disabled`

**Comment by multiOTP** [comment]
Hello HumMan,

The process to bypass multiOTP supposed that you are **ALREADY** logged in on your RDP server **AND** that your session **IS NOT LOCKED**.

In this case, when you loose the connection, the behavior of NLA is the correct one, as you don't want to have to type your Windows password and a new second authentication OTP in order to reconnect remotely to your computer were you were connected before The Credential Provider is not called during reconnection.

You are right, if you want to strongly secure the client reconnection, you can change that in your group policy, but customer experience will be a little bit more difficult in case of connection loss.

Regards,

Andre

**Comment by HumMan** [comment]
Hello Andre, 
thank you for detailed answer.
As this is correct behavior of NLA and credential providers (+ there is group policy setting for strong security), then it is not issue.
