### ISSUE TITLE
Project unable to build using VS2019

### ISSUE THREAD

**Issue by jeswin1jose** [multiOTP/multiOTPCredentialProvider#72]
The WIX project is missing and unable to build using VS2019.
Dependency issues are listed, while trying to build.

**Comment by multiOTP** [comment]
Hello,
could you please post a printscreen ?

Best regards

**Comment by jeswin1jose** [comment]
Hi,

There is no mechanism to resolve dependency. Now I have given the include paths directly in source code.

But now I am facing many linker errors.

Do you have a Repo which can be build using Visual Studio 2019 which has dependency parts being addressed ?

Regards,
Jeswin Jose

**Comment by multiOTP** [comment]
Hello Jeswin,

We will try to commit a new Visual Studio 2019 project in the weeks, including dependencies (or the link to download them).

Regards,

**Comment by jeswin1jose** [comment]
Hi,

Yes, it would be helpful as It was difficult for me to figure out all the dependencies, as I was expecting a stable version.
Can you recommend any older version, which can compile in Visual Studio ? I can manage to change the version of Visual Studio.

Regards,
Jeswin Jose

**Comment by multiOTP** [comment]
Hello Jeswin,

Dependencies are always needed, even with old version. Binary releases of multiOTP Credential Provider are stable versions using 100% of the source code here, only the build mechanism of Visual Studio is not smooth.

Stay in touch for a few days in order to check the next package, which should be easier to compile.

Regards,

**Comment by multiOTP** [comment]
Hello,
All dependencies should now be available correctly.
Check it and keep us in touch.
Regards,
